src/VNPMS/bugs/urls.py
from django.urls import re_path as url

from bugs.views import *

urlpatterns = [
    url(r'^edit/(?P<pk>\d+)/$', bug_edit, name="bug_edit"),
    url(r'^add/$', bug_create, name="bug_create"),
    url(r'^list/$', bug_list, name="bug_list"),
    url(r'^page/(?P<pk>\d+)/$', bug_page, name="bug_page"),
    url(r'^detail/(?P<pk>\d+)/$', bug_detail, name="bug_detail"),
    url(r'^delete/(?P<pk>\d+)/$', bug_delete, name="bug_delete"),
    url(r'^bfd/(?P<pk>\d+)', bug_file_delete, name="bug_file_delete"),
]

src/VNPMS/production/urls.py
from django.urls import re_path as url

from production.views import excel_import, excel_import_preview, record, get_step_info, record_detail, record_edit, \
    record_del, wo_detail, record2, record2_del, get_user_info, record_detail_sap_empno, record_manage, \
    prod_sap_export, record_export, get_mach_info, get_mtr_info, item_search

urlpatterns = [
    url(r'^import/', excel_import, name='prod_import'),
    url(r'^record/', record, name='prod_record'),
    url(r'^record2/', record2, name='prod_record2'),
    url(r'^record_edit/(?P<pk>\w+)/$', record_edit, name='prod_record_edit'),
    url(r'^record_delete/(?P<pk>\w+)/$', record_del, name='prod_record_del'),
    url(r'^record2_delete/(?P<pk>\w+)/$', record2_del, name='prod_record2_del'),
    url(r'^record_detail/$', record_detail, name='prod_record_detail'),
    url(r'^record_detail/(?P<sap_emp_no>\w+)/$', record_detail_sap_empno, name='prod_record_detail_sap_empno'),
    url(r'^record_manage/', record_manage, name='prod_record_manage'),
    url(r'^wo_detail/', wo_detail, name='prod_wo_detail'),
    url(r'^item_search/', item_search, name='prod_item_search'),
    url(r'^import_preview/', excel_import_preview, name='prod_import_preview'),
    url(r'^get_step_info/', get_step_info, name='get_step_info_api'),
    url(r'^get_user_info/', get_user_info, name='get_user_info_api'),
    url(r'^get_mach_info/', get_mach_info, name='get_mach_info_api'),
    url(r'^get_mtr_info/', get_mtr_info, name='get_mtr_info_api'),
    url(r'^prod_sap_export/', prod_sap_export, name='prod_sap_export'),
    url(r'^record_export/', record_export, name='record_export'),
]

src/VNPMS/bugs/models.py
import os

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.conf import settings


class Bug(models.Model):
    bug_no = models.CharField('Bug No.', max_length=20, unique=True)
    belong_to = models.ForeignKey(
        'requests.Request', related_name='bug_super', on_delete=models.CASCADE, null=True)  # 上層
    title = models.CharField(max_length=100)
    status = models.ForeignKey(
        'bases.Status', related_name='bug_status', on_delete=models.DO_NOTHING)
    level = models.ForeignKey(
        'requests.Level', related_name='bus_level', on_delete=models.DO_NOTHING)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='bugs', on_delete=models.DO_NOTHING, null=True)
    project = models.ForeignKey(
        'projects.Project', related_name='bug_project', on_delete=models.CASCADE)
    desc = RichTextUploadingField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)
    create_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='bug_create_at')
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='bug_update_at')

    def get_absolute_url(self):
        return reverse('bug_detail', kwargs={'pk': self.pk})


class Bug_attachment(models.Model):
    bug = models.ForeignKey(
        'Bug', related_name='bug_files', on_delete=models.CASCADE)
    files = models.FileField(upload_to='uploads/bugs/%Y/%m/')
    description = models.CharField(max_length=50, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, editable=True)


@receiver(models.signals.post_delete, sender=Bug_attachment)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.files:
        if os.path.isfile(instance.files.path):
            os.remove(instance.files.path)

src/VNPMS/production/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class ExcelTemp(models.Model):
    batch_no = models.CharField(max_length=20, primary_key=True)
    plant = models.CharField(max_length=10, blank=True, null=True)
    wo_no = models.CharField(max_length=20, blank=True, null=True)
    cfm_code = models.CharField(max_length=20, blank=True, null=True)
    ctr_code = models.CharField(max_length=20, blank=True, null=True)
    status = models.CharField(max_length=200, blank=True, null=True)
    work_center = models.CharField(max_length=20, blank=False, null=False)
    item_no = models.CharField(max_length=20, blank=True, null=True)
    spec = models.CharField(max_length=100, blank=True, null=True)
    step_no = models.CharField(max_length=20, blank=True, null=True)
    step_code = models.CharField(max_length=20, blank=True, null=True)
    step_name = models.CharField(max_length=20, blank=True, null=True)
    wo_qty = models.IntegerField(default=0)
    wo_labor_time = models.FloatField(default=0)
    wo_mach_time = models.FloatField(default=0)
    std_qty = models.IntegerField(default=0)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='wo_excel_temp_create_by')  # 建立者

class COOIS_Record(models.Model):
    batch_no = models.CharField(max_length=20, primary_key=True)
    file_name = models.CharField(max_length=50, blank=False, null=False)
    file_url = models.CharField(max_length=50, blank=False, null=False)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='coois_create_by')  # 建立者

class WOMain(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    batch_no = models.CharField(max_length=20, blank=False, null=False)
    plant = models.CharField(max_length=10, blank=False, null=False)
    wo_no = models.CharField(max_length=20, blank=False, null=False)
    item_no = models.CharField(max_length=20, blank=True, null=True)
    spec = models.CharField(max_length=100, blank=False, null=False)
    version = models.IntegerField(default=1)
    enable = models.BooleanField(default=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='wo_main_create_by')  # 建立者


class WODetail(models.Model):
    wo_main = models.ForeignKey(WOMain, related_name='wo_main', on_delete=models.CASCADE)
    work_center = models.CharField(max_length=20, blank=False, null=False)
    cfm_code = models.CharField(max_length=20, blank=True, null=True)
    ctr_code = models.CharField(max_length=20, blank=True, null=True)
    status = models.CharField(max_length=200, blank=True, null=True)
    step_no = models.CharField(max_length=20, blank=True, null=True)
    step_code = models.CharField(max_length=20, blank=True, null=True)
    step_name = models.CharField(max_length=20, blank=True, null=True)
    wo_qty = models.IntegerField(default=0)
    wo_labor_time = models.FloatField(default=0)
    wo_mach_time = models.FloatField(default=0)
    std_qty = models.IntegerField(default=0)


class Machine(models.Model):
    step_code = models.CharField(max_length=20, blank=True, null=True)
    step_name = models.CharField(max_length=20, blank=True, null=True)
    mach_code = models.CharField(max_length=20, primary_key=True)
    mach_name = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.mach_name


class Record(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    work_center = models.CharField(max_length=20, blank=False, null=False)
    plant = models.CharField(max_length=10, blank=False, null=False)
    wo_no = models.CharField(max_length=20, blank=False, null=False)
    item_no = models.CharField(max_length=20, blank=False, null=False)
    spec = models.CharField(max_length=100, blank=False, null=False)
    emp_no = models.CharField(max_length=30, blank=False, null=False)
    username = models.CharField(max_length=30, blank=False, null=False)
    sap_emp_no = models.CharField(max_length=30, blank=False, null=False)
    cfm_code = models.CharField(max_length=20, blank=False, null=False)
    ctr_code = models.CharField(max_length=20, blank=True, null=True)
    step_no = models.CharField(max_length=20, blank=True, null=True)
    step_code = models.CharField(max_length=20, blank=True, null=True)
    step_name = models.CharField(max_length=20, blank=True, null=True)
    mach = models.ForeignKey(Machine, related_name='record_mach', on_delete=models.DO_NOTHING, blank=True, null=True)
    record_dt = models.CharField(max_length=10, blank=False, null=False)
    labor_time = models.FloatField(default=0)
    mach_time = models.FloatField(default=0)
    good_qty = models.IntegerField(default=0)
    ng_qty = models.IntegerField(default=0)
    comment = models.CharField(max_length=40, blank=True, null=True)
    sap_flag = models.BooleanField(default=False)
    status = models.CharField(max_length=10, blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='record_update_by')

    def get_absolute_url(self):
        return reverse('prod_record_detail_sap_empno', kwargs={'sap_emp_no': self.sap_emp_no})


class WorkType(models.Model):
    type_code = models.CharField(max_length=5, primary_key=True)
    type_name = models.CharField(max_length=30, blank=False, null=False)
    type_name_vi = models.CharField(max_length=30, blank=False, null=False)
    type_name_en = models.CharField(max_length=30, blank=False, null=False)
    create_at = models.DateTimeField(auto_now=True, null=True)
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='worktype_create_by')


class Record2(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    emp_no = models.CharField(max_length=30, blank=False, null=False)
    sap_emp_no = models.CharField(max_length=30, blank=False, null=False)
    record_dt = models.CharField(max_length=10, blank=False, null=False)
    work_type = models.ForeignKey(WorkType, related_name='record_work_type', on_delete=models.DO_NOTHING)
    comment = models.CharField(max_length=255, blank=True, null=True)
    labor_time = models.FloatField(default=0)
    create_at = models.DateTimeField(auto_now=True, null=True)
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='record2_create_by')
    qty = models.IntegerField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('prod_record_detail_sap_empno', kwargs={'sap_emp_no': self.sap_emp_no})


class Consumption(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    plant = models.CharField(max_length=10, blank=False, null=False)
    cfm_code = models.CharField(max_length=20, blank=False, null=False)
    wo_no = models.CharField(max_length=20, blank=False, null=False)
    wo_mtrl_no = models.CharField(max_length=20, blank=False, null=False)
    item_no = models.CharField(max_length=20, blank=False, null=False)
    qty = models.FloatField(default=0)
    sap_flag = models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now=True, null=True)
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='consumption_create_by')

class Sync_SAP_Log(models.Model):
    function = models.CharField(max_length=20, blank=False, null=False)
    batch_no = models.CharField(max_length=20, blank=False, null=False)
    file_name = models.CharField(max_length=30, blank=True, null=True)
    amount = models.IntegerField(default=0)
    create_at = models.DateTimeField(auto_now=True, null=True)
    create_by = models.CharField(max_length=20)


class Series(models.Model):
    function = models.CharField(max_length=20)
    key = models.CharField(max_length=20)
    series = models.IntegerField()

    class Meta:
        unique_together = (("function", "key"),)

src/VNPMS/production/templates/production/base.html
{% extends 'bases/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}
{% block title %}
Production
{% endblock %}
{% block breadcrumb %}

{% endblock %}
{% block container %}
<div class="card-header">
    <div class="row">
        <div class="col">
            <a href="{% url 'prod_record' %}" class="btn btn-info">{% trans 'Record Add' %}</a>
            <a href="{% url 'prod_record_detail' %}" class="btn btn-info">{% trans 'Record Search' %}</a>
            {% if user.is_authenticated %}
                <a href="{% url 'prod_wo_detail' %}" class="btn btn-info">工單查詢</a>
                <a href="{% url 'prod_item_search' %}" class="btn btn-info">料號查詢</a>
                {% if perms.users.perm_workhour %}
                <a href="{% url 'prod_record_manage' %}" class="btn btn-info">管理報表</a>
                <a href="{% url 'prod_import' %}" class="btn btn-info">工單匯入</a>
                <a href="{% url 'prod_sap_export' %}" class="btn btn-info">SAP對接</a>
                <a href="{% url 'record_export' %}" class="btn btn-info">報工下載</a>
                {% endif %}
            {% endif %}
        </div>
        <div class="pr-3">
        {% include 'bases/lang.html' %}
        </div>
        {% if user.is_authenticated %}
        <div class="ml-md-auto">
            <a class="btn btn-info" href="{% url 'logout' %}" role="button"><i class="fas fa-sign-out-alt"></i>{% trans "logout" %} ({{ user.username }})</a>
        </div>
        {% endif %}
    </div>
</div>

{% block content %}
{% endblock content %}
{% endblock %}
{% block base_js %}
<script>
var error_msg = "{{ error_msg }}";
if(error_msg.length>0) {
    alert(error_msg);
}
</script>
{% endblock base_js %}

src/VNPMS/production/templates/production/import.html
{% extends 'production/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block js %}
<script>
    $(document).ready(function() {
        $("#import_form").submit(function(e) {
            $("body").loading();
            if($("#send").text()=="Preview")
            {
                e.preventDefault();
                var formData = new FormData(this);
                $.ajax({
                    type: "POST",
                    url: "{% url 'prod_import_preview' %}",
                    data: formData,
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert(jqXHR.responseText);
                    },
                    success: function(data) {
                        $("#preview").html(data);
                        $("#send").text("Save");
                        $("body").loading("stop");
                        console.log(data)
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                })
            }
            else {
                $("#preview").html("");
            }
        });
    });

</script>
{% endblock js %}
{% block content %}

<div class="pt-3">
    <ul class="nav nav-tabs mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="import-tab" data-toggle="pill" href="#import" role="tab" aria-controls="import" aria-selected="true">匯入資料</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="upload-record-tab" data-toggle="pill" href="#upload-record" role="tab" aria-controls="upload-record" aria-selected="false">匯入紀錄</a>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="import" role="tabpanel" aria-labelledby="import-tab">
            <div style="background-color: #EEEEEE;border-radius: .3rem;padding: 1rem 1rem;">
                <h1 class="display-5">匯入說明</h1>
                <p class="lead">※系統限制工單狀態有PRT才能匯入</p>
                <p class="lead">※工單可以重覆上傳，以最後一次上傳為主</p>
            </div>
            <div class="p-4">
            <form action="" method="post" class="form-group font-weight-bold align-middle" id="import_form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                    <div>請選擇Template檔案(*.xlsx)
                        <a href="{% static "production/coois.xlsx" %}" target="_blank">下載範本檔</a>
                    </div>
                    <div class="row">
                        <div id="div_id_files" class="form-group">
                            <input name="files1" accept=".xls,.xlsx" class="clearablefileinput" id="id_files" type="file">
                            <button type="submit" class="btn btn-primary" id="send">Preview</button>
                        </div>
                    </div>
                    <div class="row" id="preview">
                        {{ preview | safe }}
                    </div>
                </div>
            </form>
            </div>
        </div>
        <div class="tab-pane fade" id="upload-record" role="tabpanel" aria-labelledby="upload-record-tab">
            <div class="p-3">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th width="20%">上傳時間</th>
                        <th width="20%">上傳者</th>
                        <th width="30%">檔案名稱</th>
                        <th width="20%">下載</th>
                    </tr>
                    {% for coois in cooises %}
                    <tr>
                        <td>{{ coois.create_at }}</td>
                        <td>{{ coois.create_by }}</td>
                        <td>{{ coois.file_name }}</td>
                        <td><a href="{{ coois.file_url }}" class="btn btn-light">下載</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

src/VNPMS/production/templates/production/item_search.html
{% extends 'production/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block ready %}
$("#id_wo_no").focus();
{% endblock ready %}
{% block js %}
<script>
    var wo = {
        'info': function(wo_no) {
          $("#wo_no").val(wo_no);
          $("#wo_form").submit();
        }
    };

</script>
{% endblock js %}
{% block content %}
    <form id="wo_form" action="{% url 'prod_wo_detail' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="wo_no" id="wo_no">
    </form>
    <div class="row">
        <div class="col">

        </div>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <form action="{% url 'prod_item_search' %}" method="POST">
                {% csrf_token %}
                {% crispy form %}
            </form>
            <table border="1" class='table table-bordered table-striped'>
                <tr>
                    <th>工單</th>
                    <th>料號</th>
                    <th>料號說明</th>
                    <th>建立日期</th>
                </tr>
                {% for wo in wos %}
                <tr onclick="wo.info('{{ wo.wo_no }}');" style="cursor: pointer;">
                    <td>{{ wo.wo_no }}</td>
                    <td>{{ wo.item_no }}</td>
                    <td>{{ wo.spec }}</td>
                    <td>{{ wo.create_at|date:'Y-m-d' }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-1"></div>
    </div>

{% endblock %}

src/VNPMS/production/templates/production/record_detail.html
{% extends 'production/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block ready %}

{% endblock ready %}
{% block js %}
<script>
function record2_submit() {
    $("#hid_sap_emp_no").val($("#id_sap_emp_no").val());
}
</script>
{% endblock js %}
{% block content %}
    <div class="row pt-3">
        <div class="col-1"></div>
        <div class="col-10">
            <form action="{% url 'prod_record_detail' %}" method="POST">
                {% csrf_token %}
                {% crispy form %}
            </form>
            <form id="record2_form" method='POST' action='/production/record2/'>
            {{ html|safe }}
            </form>

        </div>
        <div class="col-1"></div>
    </div>

{% endblock %}

src/VNPMS/production/templates/production/record_excel.html
{% extends 'production/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block ready %}

{% endblock ready %}
{% block css %}

{% endblock css %}
{% block js %}

{% endblock js %}
{% block content %}
<div class="card">
    <div class="card-header pb-1 pt-1">
        <div class="row">
            查詢條件
        </div>
    </div>
    <div class="card-body">
        <form action="{% url 'record_export' %}" method="post" class="form-group font-weight-bold align-middle" id="request_form" enctype="multipart/form-data">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
</div>
{% endblock %}

src/VNPMS/production/templates/production/record_manage.html
{% extends 'production/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block ready %}

{% endblock ready %}
{% block css %}
<style>
/* 會員清單的標題列要可以點擊排序 */
/* #member_data > table > thead > tr > th:not(:nth-child(1)) { */
#key_user > table > thead > tr > th {
    cursor: pointer;
}

.data-row {
    cursor: pointer;
}
</style>
{% endblock css %}
{% block js %}
<script src="{% static 'base\js\jquery.redirect.js' %}"></script>
<script>
    var key_user = {
      'info': function(sap_emp_no) {
          var record_dt = $("#id_record_dt").val();
          $.redirect('{% url 'prod_record_detail' %}', {'record_dt': record_dt, 'sap_emp_no': sap_emp_no, 'csrfmiddlewaretoken': '{{csrf_token}}'});
      }
    };
</script>
{% endblock js %}
{% block content %}
<div class="row pt-3">
    <div class="col-1"></div>
    <div class="col-10">
        <form action="{% url 'prod_record_manage' %}" method="POST">
            {% csrf_token %}
            {% crispy form %}
        </form>
        <div id="key_user" class="table-responsive">
            <table border="1" class="table table-bordered table-striped table-hover">
                <thead>
                    <tr class="text-center table-active" style="display: table;table-layout: fixed;width: 100%;">
                        <th style="text-align: center;">SAP員編</th>
                        <th style="text-align: center;">姓名</th>
                        <th style="text-align: center;">人時(分)</th>
                        <th style="text-align: center;">機時(分)</th>
                        {% for worktype in worktypes %}
                        <th style="text-align: center">{{ worktype.type_name }}</th>
                        {% endfor %}
                        <th style="text-align: center;">總人時</th>
                    </tr>
                </thead>
                <tbody style="height:600px; overflow:auto;display: block;">
                    {% for record in records %}
                    <tr style="display: table;table-layout: fixed;width: 100%;text-align: center" onclick="key_user.info('{{ record.sap_emp_no }}');" class="data-row">
                        <td>{{ record.sap_emp_no }}</td>
                        <td>{{ record.username }}</td>
                        <td>{{ record.labor_time }}</td>
                        <td>{{ record.mach_time }}</td>
                        {{ record.html|safe }}
                        <td style="{{ record.css_overtime }}">{{ record.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-1"></div>
</div>
{% endblock %}

src/VNPMS/production/templates/production/wo_detail.html
{% extends 'production/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block ready %}
$("#id_wo_no").focus();
{% endblock ready %}
{% block js %}
<script>

</script>
{% endblock js %}
{% block content %}
    <div class="row">
        <div class="col">

        </div>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <form action="{% url 'prod_wo_detail' %}" method="POST">
                {% csrf_token %}
                {% crispy form %}
            </form>
            <div class="row p-3">
                <div class="col-3">料號：{{ item_no }}</div>
                <div class="col-9">料號說明：{{ spec }}</div>
            </div>
            <table border="1" class='table table-bordered table-striped'>
                <tr>
                    <th>工單</th>
                    <th>加工順序</th>
                    <th>作業代碼</th>
                    <th>作業短文</th>
                    <th>工單數量</th>
                    <th>良品</th>
                    <th>NG</th>
                    <th>基礎數量</th>
                    <th>標準機時</th>
                    <th>實際機時(MIN)</th>
                    <th>標準人時</th>
                    <th>實際人時(MIN)</th>
                </tr>
                {% for step in steps %}
                    {% for work_reocrd in step.work_records %}
                        <tr style="background-color: white">
                            <td colspan="2" style="text-align: right">{{ work_reocrd.comment|default:"" }}┏</td>
                            <td style="text-align: center">{{ work_reocrd.record_dt }}</td>
                            <td style="text-align: center">{{ work_reocrd.sap_emp_no }}</td>
                            <td style="text-align: center">{{ work_reocrd.username }}</td>
                            <td style="color: blue;font-weight:bold;text-align: right">{{ work_reocrd.good_qty }}</td>
                            <td style="color: blue;font-weight:bold;text-align: right">{{ work_reocrd.ng_qty }}</td>
                            <td colspan="2"></td>
                            <td style="color: blue;font-weight:bold;text-align: right">{{ work_reocrd.mach_time }}</td>
                            <td></td>
                            <td style="color: blue;font-weight:bold;text-align: right">{{ work_reocrd.labor_time }}</td>
                        </tr>
                    {% endfor %}
                <tr style="background-color: rgba(0,0,0,.05)">
                    <td>{{ wo_no }}</td>
                    <td>{{ step.step_no }}</td>
                    <td>{{ step.step_code }}</td>
                    <td>{{ step.step_name }}</td>
                    <td style="text-align: right">{{ step.wo_qty }}</td>
                    <td style="color: blue;font-weight:bold;text-align: right">{{ step.step_good_qty }}</td>
                    <td style="color: blue;font-weight:bold;text-align: right">{{ step.step_ng_qty }}</td>
                    <td style="text-align: right">{{ step.std_qty }}</td>
                    <td style="text-align: right">{{ step.std_mach_time }}</td>
                    <td style="color: blue;font-weight:bold;text-align: right">{{ step.step_mach_time }}</td>
                    <td style="text-align: right">{{ step.std_labor_time }}</td>
                    <td style="color: blue;font-weight:bold;text-align: right">{{ step.step_labor_time }}</td>
                </tr>
            {% endfor %}
            </table>
        </div>
        <div class="col-1"></div>
    </div>

{% endblock %}