src/VNPMS/bases/urls.py
from django.urls import re_path as url
from bases.views import change_status, index

urlpatterns = [
    url(r'^change_status$', change_status, name='change_status'),
    url(r'^', index, name='index'),
]

src/VNPMS/bugs/urls.py
from django.urls import re_path as url

from bugs.views import *

urlpatterns = [
    url(r'^edit/(?P<pk>\d+)/$', bug_edit, name="bug_edit"),
    url(r'^add/$', bug_create, name="bug_create"),
    url(r'^list/$', bug_list, name="bug_list"),
    url(r'^page/(?P<pk>\d+)/$', bug_page, name="bug_page"),
    url(r'^detail/(?P<pk>\d+)/$', bug_detail, name="bug_detail"),
    url(r'^delete/(?P<pk>\d+)/$', bug_delete, name="bug_delete"),
    url(r'^bfd/(?P<pk>\d+)', bug_file_delete, name="bug_file_delete"),
]

src/VNPMS/bases/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings


class Status(models.Model):
    status_en = models.CharField(max_length=50)
    status_cn = models.CharField(max_length=50)
    status_desc = models.TextField()
    process_rate = models.IntegerField(default=0)
    create_at = models.DateTimeField(default=timezone.now)
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='status_create_at')
    update_at = models.DateTimeField(default=timezone.now)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='status_update_at')

    def __str__(self):
        return self.status_en


class DataIndex(models.Model):
    project = models.ForeignKey(
        'projects.Project', related_name='index_project', on_delete=models.CASCADE)
    data_type = models.CharField(max_length=10)
    data_date = models.CharField(max_length=8)
    current = models.IntegerField(default=0, null=True, blank=True)
    update_at = models.DateTimeField(default=timezone.now)


class FormType(models.Model):
    tid = models.IntegerField()
    type = models.CharField(max_length=8)
    short_name = models.CharField(max_length=3, null=False)

src/VNPMS/bugs/models.py
import os

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.conf import settings


class Bug(models.Model):
    bug_no = models.CharField('Bug No.', max_length=20, unique=True)
    belong_to = models.ForeignKey(
        'requests.Request', related_name='bug_super', on_delete=models.CASCADE, null=True)  # 上層
    title = models.CharField(max_length=100)
    status = models.ForeignKey(
        'bases.Status', related_name='bug_status', on_delete=models.DO_NOTHING)
    level = models.ForeignKey(
        'requests.Level', related_name='bus_level', on_delete=models.DO_NOTHING)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='bugs', on_delete=models.DO_NOTHING, null=True)
    project = models.ForeignKey(
        'projects.Project', related_name='bug_project', on_delete=models.CASCADE)
    desc = RichTextUploadingField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)
    create_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='bug_create_at')
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='bug_update_at')

    def get_absolute_url(self):
        return reverse('bug_detail', kwargs={'pk': self.pk})


class Bug_attachment(models.Model):
    bug = models.ForeignKey(
        'Bug', related_name='bug_files', on_delete=models.CASCADE)
    files = models.FileField(upload_to='uploads/bugs/%Y/%m/')
    description = models.CharField(max_length=50, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, editable=True)


@receiver(models.signals.post_delete, sender=Bug_attachment)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.files:
        if os.path.isfile(instance.files.path):
            os.remove(instance.files.path)

src/VNPMS/bases/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from bases.models import Status
from requests.models import Request
from requests.utils import update_process_rate


@login_required
def index(request):
    return render(request, 'bases/index.html', locals())
    #return redirect(reverse('assets_main'))


def change_status(request):
    request_no = request.POST.get('request_no')
    new_status = request.POST.get('new_status')
    o_new_status = Status.objects.get(pk=new_status)
    the_request = Request.objects.filter(request_no=request_no).first()
    the_request.status = o_new_status
    the_request.process_rate = update_process_rate(the_request.request_no, o_new_status)
    the_request.save()

    result = {'message': 'good'}

    return JsonResponse(result, safe=False)


def get_user_setting_pagenum(request):
    page_num = 5
    # 取得使用者專案設定
    if request.user.setting_user:
        project_setting = request.user.setting_user.first()
        page_num = project_setting.page_number
    return page_num

src/VNPMS/bases/templates/bases/attach_form.html
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
<form action="" method="post" class="form-group font-weight-bold align-middle" id="request_form" enctype="multipart/form-data">
  <div class="card-body">
    {% csrf_token %}
    {% crispy form %}
      <hr />
      <div>{% trans "attachment" %}</div>
      <div class="row">
            <div id="div_id_files" class="form-group col-2">
                <label for="id_files" class="form-control-label">{% trans "file" %} 1</label>
                <input name="files1" class="clearablefileinput" id="id_files" type="file">
            </div>
            <div id="div_id_description" class="form-group col-10">
                <label for="id_description" class="form-control-label ">{% trans "desc" %}：</label>
                <input name="description1" maxlength="50" class="textinput textInput form-control" id="id_description" type="text">
            </div>
        </div>
      <div class="row">
            <div id="div_id_files" class="form-group col-2">
                <label for="id_files" class="form-control-label">{% trans "file" %} 2</label>
                <input name="files2" class="clearablefileinput" id="id_files" type="file">
            </div>
            <div id="div_id_description" class="form-group col-10">
                <label for="id_description" class="form-control-label ">{% trans "desc" %}：</label>
                <input name="description2" maxlength="50" class="textInput form-control" id="id_description" type="text">
            </div>
        </div>
  </div>
  <div class="card-footer text-center">
    <button type="submit" class="btn btn-primary" id="send">{% trans "save" %}</button>
      <input type="button" class="btn btn-secondary" value="{% trans 'Cancel' %}" onClick="javascript:history.go(-1);">
  </div>
</form>

src/VNPMS/bases/templates/bases/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Noah - {% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'jquery-ui\jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-4.1.3\css\bootstrap.min.css' %}">
    <script src="{% static 'base\js\umd\popper.js' %}"></script>
    <script src="{% static 'base\js\func.js' %}"></script>
    <script src="{% static 'jquery\jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'jquery-ui\jquery-ui.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.3\js\bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'fontawesome-5.4.2\css\all.css' %}">
    <link href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="https://unpkg.com/bootstrap-table@1.22.1/dist/extensions/fixed-columns/bootstrap-table-fixed-columns.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.22.1/dist/extensions/fixed-columns/bootstrap-table-fixed-columns.min.js"></script>
    <!-- jquery-loading v1.3.0 -->
    <link href="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.js"></script>



    <style type="text/css">
        input:required {
            background: #ffffe7;
        }

        select:required {
            background: #ffffe7;
        }

        .content {
            color: blue;
        }

        .django-ckeditor-widget{
            display: inline !important;
        }

        img{
            max-width:100%;
        }
        th{
            font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
        }
        td{
            font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
        }
        option{
            font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
        }
        a{
            font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
        }
        div{
            font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
        }
        html, body {
            height: 100%;
        }
        /* width */
        ::-webkit-scrollbar {
            width: 5px;
            height: 5px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
          background: #f1f1f1;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
          background: #888;
            border-radius: 5px;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
          background: #555;
        }

        .box-nav {
            text-align: center;
            padding-top: 60px;
            width:55px;
            background-color: #F7F7F7;
            border-right:1px solid #CCC;
            height:100vh;
            position: fixed;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .box-nav-btn {
            margin-top: 5px;
            width: 50px;
            height: 50px;
            display: block;
        }

        .box-nav a {
            color: #CCC;
        }

        .box-nav a:hover {
            color: #000;
        }

        /* Image inside table */
        table img {
            max-width: 100%;
            max-height: 400px;
            width: auto;
            height: auto;
            display: block;
            cursor: pointer;
        }

        /* Fullscreen modal */
        #imgModal {
            display: none;
            position: fixed;
            z-index: 1000;
            padding-top: 50px;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0.8);
        }

        /* Modal image */
        #imgModalContent {
            margin: auto;
            display: block;
            max-width: 80vw;
            border-radius: 4px;
        }

        /* Close button */
        #imgModalClose {
            position: absolute;
            top: 20px;
            right: 35px;
            color: #fff;
            font-size: 40px;
            font-weight: bold;
            cursor: pointer;
        }


    </style>
    {% block head %}
    {% endblock %}
    {% block css %}

    {% endblock css %}
    {% block base_js %}

    {% endblock base_js %}
    {% block js %}

    {% endblock js %}
    <script>
        $(document).ready(function() {
               {% block ready %}
               {% endblock ready %}
        });
    </script>
</head>
<body>
<div style="display: flex;width: 100%;height: auto; z-index: 9998">
    <div style="margin-right: 55px">
        {% if user.is_authenticated %}
        <div class="box-nav">
            <div class="d-flex flex-column align-items-center" style="margin-bottom: auto">
                <a class="box-nav-btn" style="font-size: 20px;" href="{% url 'problem_feed' %}" role="button"
                   data-bs-toggle="tooltip" data-bs-placement="right" title="{% trans 'Your problem feed' %}">
                    <i class="fa fa-list-alt" style="z-index: 9999" aria-hidden="true"></i>
                </a>
                {% if request.user.user_type.type_name != "Requester" %}
                    <a class="box-nav-btn" href="{% url 'pms_home' %}" role="button" data-bs-toggle="tooltip"
                       data-bs-placement="right" title="{% trans 'Project Management System' %}">
                        <i class="fa fa-tasks"></i>
                    </a>
                {% endif %}
                {% if request.user.user_type.type_name == "Administrator" %}
                    <a class="box-nav-btn" href="{% url 'group_management' %}" role="button" data-bs-toggle="tooltip"
                       data-bs-placement="right" title="{% trans 'Group' %}">
                        <i class="fa fa-users" aria-hidden="true"></i>
                    </a>
                {% endif %}
                <a class="box-nav-btn" href="{% url 'user_info' %}" role="button" data-bs-toggle="tooltip"
                   data-bs-placement="right" title="{% trans 'Personal Setting' %}">
                    <i class="fas fa-cog"></i>
                </a>
                {% if perms.users.perm_user_manage %}
                    <a class="box-nav-btn" href="{% url 'user_list' %}" role="button" data-bs-toggle="tooltip"
                       data-bs-placement="right" title="{% trans 'Authority Management' %}">
                        <i class="fas fa-cogs"></i>
                    </a>
                {% endif %}
            </div>

            <div class="mb-5">
                {% if user.is_authenticated %}
                    <a class="btn btn-info text-white" href="{% url 'logout' %}" role="button"><i class="fas fa-sign-out-alt"></i></a>
                {% else %}
                    <a class="btn btn-info" href="#">{% trans "login" %}</a>
                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>
    <div style="width: 100%;height:900px">
        {% block container %}

        {% endblock %}
    </div>
</div>
<div id="imgModal">
    <span id="imgModalClose">&times;</span>
    <img id="imgModalContent" src="">
</div>
</body>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const modal = document.getElementById("imgModal");
        const modalImg = document.getElementById("imgModalContent");
        const closeBtn = document.getElementById("imgModalClose");

        document.querySelectorAll("table img").forEach(img => {
            img.addEventListener("click", () => {
                modal.style.display = "block";
                modalImg.src = img.src;
            });
        });

        closeBtn.onclick = function () {
            modal.style.display = "none";
            modalImg.src = "";
        };

        window.onclick = function (event) {
            if (event.target === modal) {
                modal.style.display = "none";
                modalImg.src = "";
            }
        };
    });
</script>
</html>

src/VNPMS/bases/templates/bases/footer.html
<footer class="footer">
       <div class="text-center text-muted"><small>IT Operations Management System Version 1.0a</small></div>
</footer>

src/VNPMS/bases/templates/bases/form.html
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
<form action="" method="post" class="form-group font-weight-bold align-middle" id="request_form" enctype="multipart/form-data">
  <div class="card-body">
    {% csrf_token %}
    {% crispy form %}
  </div>
  <div class="card-footer text-center">
    <button type="submit" class="btn btn-primary" id="send">{% trans "save" %}</button>
</div>
</form>

src/VNPMS/bases/templates/bases/index.html
{% extends 'bases/base.html' %}

{% load static %}
{% load i18n %}
{% block head %}

{% endblock %}
{% block title %}
Index
{% endblock title %}
{% block breadcrumb %}

{% endblock %}
{% block container %}
<div class="card-header">
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col"><h2></h2></div>
        <div class="pr-3">
        {% include 'bases/lang.html' %}
        </div>
        <div class="ml-md-auto">
            <a class="btn btn-info" href="{% url 'logout' %}" role="button"><i class="fas fa-sign-out-alt"></i>{% trans "logout" %} ({{ user.username }})</a>
        </div>
    </div>
    {% endif %}
</div>
<div class="row justify-content-center align-items-center" style="height:500px">
    <div class="col" style="text-align:center">
        <img src="{% static '/pictures/index.jpg' %}">
    </div>
</div>
{% endblock %}

src/VNPMS/bases/templates/bases/lang.html
{% load i18n %}

<form action="{% url 'set_language' %}" method="post" >{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}"/>
    <select name="language" class="form-control" onchange="this.form.submit()">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            {% if language.code == 'vi' %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                        selected{% endif %}>
                    {{ language.name_local }} ({{ language.code }})
                </option>
            {% endif %}
        {% endfor %}
        {% for language in languages %}
            {% if language.code == 'en' %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                        selected{% endif %}>
                    {{ language.name_local }} ({{ language.code }})
                </option>
            {% endif %}
        {% endfor %}
        {% for language in languages %}
            {% if language.code == 'zh-hant' %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                        selected{% endif %}>
                    {{ language.name_local }} ({{ language.code }})
                </option>
            {% endif %}
        {% endfor %}
    </select>
</form>

src/VNPMS/bases/templates/bases/menu_base.html
{# default/menu_base.html #}

{% extends "bases/base.html" %} {% load static %}
{% load settings_tags %}
{% load i18n %}
{% block title %} {{ block.super}} {% endblock title %}

{% block css %}
{{ block.super}}
{% endblock css %}

{% block container %}
    <form method="post" action="{% url 'search' %}">
    {% csrf_token %}
    <nav class="navbar navbar-default navbar-expand-lg navbar-static-top navbar-dark bg-dark" role="navigation">
        {% if request.user %}
            <a class="navbar-brand" href="{% url 'pms_home' %}"><span style="font-family: Arial Black">PMS</span></a>
        {% endif %}
        <small class="text-light">

        </small>
        <div class="collapse navbar-collapse justify-content-end">
                <input class="form-control col-2" type="text" placeholder="{% trans 'keyword' %}" name="keywords">&nbsp;
                <button type="submit" class="btn btn-warning">{% trans "Search" %}</button>
            <div class="ml-4 mr-4">
                <a class="text-warning" href="{% url 'project_setting' %}"><i class="fas fa-cog fa-2x"></i></a>
            </div>
            <div>
                {% if user.is_authenticated %}
                    <a class="btn btn-info" href="{% url 'logout' %}" role="button"><i class="fas fa-sign-out-alt"></i>{% trans "logout" %} ({{ user.username }})</a>
                {% else %}
                    <a class="btn btn-info" href="#">{% trans "login" %}</a>
                {% endif %}
            </div>
        </div>

    </nav>
    </form>
    <div class="container-fluid bg-light">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb" style="padding:0px 20px">
                {% block breadcrumb %}
                    <li class="breadcrumb-item"><a href="{% url 'pms_home' %}">{% trans "Home" %}</a></li>
                {% endblock %}

            </ol>
        </nav>
        {% block content %}
        {% endblock content %}
    </div>

{% endblock container %}

{% block js %}

{% endblock js %}

src/VNPMS/bases/templates/bases/navbar.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#" title="Dashboard">
            <img src="{%  static 'base/it-3.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            IT-PMS
        </a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    </nav>
</header>

src/VNPMS/bases/templates/bases/paginating.html
<!--頁碼實現-->
<ul class="pagination">
    <li class="page-item">
    <!--判斷是否有上一頁-->
    {% if page_results.has_previous %}
        <a class="page-link" href="?page={{ page_results.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span></a>
    {% else %}
        <span class="page-link" aria-hidden="true">&laquo;</span>
    {% endif %}
    </li>
    {% for page_num in page_results.paginator.page_range%}
    <li class="page-item">
        {% if page_number == page_num %}
        <a class="page-link" style="background-color: #d8d8d8" href="?page={{ page_num }}">{{ page_num }}</a>
        {% else %}
        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        {% endif %}
    </li>
    {% endfor %}
    <!--是否有下一頁 -->
    <li class="page-item">
    <!--判斷是否有上一頁-->
    {% if page_results.has_next %}
        <a class="page-link" href="?page={{ page_results.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    {% else %}
        <span class="page-link" aria-hidden="true">&raquo;</span>
    {% endif %}
    </li>
</ul>

src/VNPMS/bases/templates/bases/sidenav.html
<div class="page-main zindex-dropdown" role="main">
    <aside>
        <ul>
            <li><a href="#">資產管理</a></li>
            <li><a href="#">設備借用</a></li>
            <li><a href="#">專案管理</a></li>
            <li><a href="#">個人設定</a></li>
            <li><a href="#">系統權限</a></li>
        </ul>
        <button class="sidenav_btn">></button>
    </aside>
</div>